server:
    port: 8081

spring:
    application:
        name: auth-service

    datasource:
        url: jdbc:postgresql://localhost:5432/slackclone
        username: postgres
        password: postgres

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

jwt:
  secret: mySuperSecretJwtKeyThatMustBeAtLeast32CharactersLong
  expiration: 86400000